name: Build assertion

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2-beta
              with:
                  fetch-depth: 1
            - name: Installing packages
              run: npm install
            - name: Build
              run: npm run build
            - name: Test the build
              run: npm run test
